if [ -f ~/.sh_alias ]; then
    source ~/.sh_alias
fi

# zsh-completionsプラグインを利用
# 事前にインストールしておく
# $ brew install zsh-completions
fpath=(/usr/local/share/zsh-completions/(N-/) $fpath)

# ディレクトリ指定だけで移動する
setopt AUTO_CD

# cdの履歴を保存して `cd + Tab` で補完
setopt AUTO_PUSHD
autoload -Uz compinit
compinit

# 単語区切りに `/` を追加
autoload -Uz select-word-style
select-word-style default
zstyle ':zle:*' word-chars " /=;@:{},|"
zstyle ':zle:*' word-style unspecified

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

# プロンプトの設定
PROMPT="%m%# "
RPROMPT="[%~ %*]"

# 候補が3以上でカーソル選択
zstyle ':completion:*:default' menu select=3

# 大文字と小文字を区別しない
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

# コマンド履歴設定
HISTFILE=~/.zsh_history
HISTSISE=1000000
SAVEHIST=1000000

# cdr を使う設定
autoload -Uz add-zsh-hook
autoload -Uz chpwd_recent_dirs cdr
add-zsh-hook chpwd chpwd_recent_dirs
# 保存する履歴の数
zstyle ':chpwd:*' recent-dirs-max 200
# cdr が cd も兼ねる
zstyle ':chpwd:*' recent-dirs-default true

